### ISSUE TITLE
Provide game JSON as a new view

### ISSUE THREAD

**Issue by dhmay** [DerbyStats/wsproxy#1]
# Request

Add a new view in wsproxy that serves:
* all the game JSON 
    * (or, optionally, all the game JSON after a specified wallclock time, plus all the roster information)
* the timestamp of the last JSON update

Storing all the game JSON would be a significant increase in storage. But it would allow anyone to build Jamstats plots for the game, both while it's live and after it's over.

# Background

I would like to get derby game data away from the track, onto the Internet, so that Jamstats can consume it.

I had been thinking of setting Jamstats up as a client of the wsproxy run at the track, but that would be complicated for the person running Jamstats, who would need to expose their laptop to the internet.

Then I realized that you're already running live.derbystats.eu! You've already made all the infrastructure for someone interested in a specific derby game to get info about that game.

**Comment by JestHerDerby** [comment]
You can already access that information via WS, using the usual scoreboard WS protocol.

Jamstats only needs to be able to talk to derbystats.eu over HTTPS for this. 
Wsmux does not make outbound connections.

**Comment by dhmay** [comment]
Oh! I've tried connecting to, e.g.:

https://jammer-lane.derbystats.eu:443

Is that the right URL and port? Or should I be connecting to some subdirectory like WS or ws or something?

Sorry if this is already documented somewhere.

**Comment by dhmay** [comment]
I'm getting this:

`-----------------------
2023-04-01 09:49:30,106 | websocket |  DEBUG: -----------------------
--- response header ---
2023-04-01 09:49:30,106 | websocket |  DEBUG: --- response header ---
HTTP/1.1 400 Bad Request
2023-04-01 09:49:30,310 | websocket |  DEBUG: HTTP/1.1 400 Bad Request
Date: Sat, 01 Apr 2023 16:49:31 GMT
2023-04-01 09:49:30,311 | websocket |  DEBUG: Date: Sat, 01 Apr 2023 16:49:31 GMT
Server: Apache/2.4.41 (Ubuntu)
2023-04-01 09:49:30,311 | websocket |  DEBUG: Server: Apache/2.4.41 (Ubuntu)
Content-Length: 445
2023-04-01 09:49:30,311 | websocket |  DEBUG: Content-Length: 445
Connection: close
2023-04-01 09:49:30,311 | websocket |  DEBUG: Connection: close
Content-Type: text/html; charset=iso-8859-1
2023-04-01 09:49:30,312 | websocket |  DEBUG: Content-Type: text/html; charset=iso-8859-1
-----------------------
`

**Comment by JestHerDerby** [comment]
There's not enough there to tell what's going on, the issue is on your end I suspect though.

**Comment by dhmay** [comment]
What protocol should I be using? http, https, ws or wss?

And what port should I be using? 443?

And is jammer-lane.derbystats.eu the correct url, or should there be something after ".eu"?

Can you give me an example of some code that's connecting with websockets to derbystats.eu successfully?

**Comment by JestHerDerby** [comment]
WSS on 443. That's a correct URL. Wsproxy is such code, as is the JS of the scoreboard.

**Comment by dhmay** [comment]
OH!!! I GOT IT! I found this in the code:

	http.HandleFunc("/WS/", func(w http.ResponseWriter, r *http.Request) { proxy.WSHTTPHandler(w, r, wsl, logger) })

And that gave me the hint that the endpoint I want is "/WS", and I tried that with wss, and it's working!!

**Comment by dhmay** [comment]
FYI:
https://github.com/dhmay/jamstats/releases/tag/v1.1.2
